[2025-09-24 11:21:04] - logger:_log - INFO - Logger initialized. Logs will be saved to C:\internship\Prodify-V2.0\logs\log.txt
[2025-09-24 11:21:11] - __init__:wrapper - DEBUG - matplotlib data path: C:\Users\os255022\AppData\Local\anaconda3\envs\iteration8\Lib\site-packages\matplotlib\mpl-data
[2025-09-24 11:21:11] - __init__:wrapper - DEBUG - CONFIGDIR=C:\Users\os255022\.matplotlib
[2025-09-24 11:21:11] - __init__:<module> - DEBUG - interactive is False
[2025-09-24 11:21:11] - __init__:<module> - DEBUG - platform is win32
[2025-09-24 11:21:11] - __init__:wrapper - DEBUG - CACHEDIR=C:\Users\os255022\.matplotlib
[2025-09-24 11:21:11] - font_manager:_load_fontmanager - DEBUG - Using fontManager instance from C:\Users\os255022\.matplotlib\fontlist-v390.json
[2025-09-24 11:21:30] - logger:_log - INFO - TeradataDatabase instance initialized
[2025-09-24 11:21:30] - logger:_log - INFO - Operation 'Database connection' started - Details: {'host': 'iteration7-gwyyqrtdecxxq4xk.env.clearscape.teradata.com', 'database': 'demo_user'}
[2025-09-24 11:21:38] - logger:_log - INFO - Operation 'Database connection' completed
[2025-09-24 11:21:38] - logger:_log - INFO - Loading a CSV file of path `c:\internship\Prodify-V2.0\data\full_train_dataset.csv`.
[2025-09-24 11:21:38] - logger:_log - INFO - Loading a CSV file of path `c:\internship\Prodify-V2.0\data\full_test_dataset.csv`.
[2025-09-24 11:21:38] - logger:_log - INFO - Starting to train `TF-IDF Classifier`.
[2025-09-24 11:21:38] - logger:_log - INFO - Loading tfidf classifier model.
[2025-09-24 11:21:38] - logger:_log - INFO - Loading tfidf classifier model is done.
[2025-09-24 11:21:38] - logger:_log - INFO - Training the model
[2025-09-24 11:22:49] - logger:write - ERROR - Traceback (most recent call last):
[2025-09-24 11:22:49] - logger:write - ERROR -   File "c:\internship\Prodify-V2.0\src\run_ensemble.py", line 13, in <module>
[2025-09-24 11:22:49] - logger:write - ERROR - main()  File "c:\internship\Prodify-V2.0\src\run_ensemble.py", line 9, in main
[2025-09-24 11:22:49] - logger:write - ERROR - run_pipeline()  File "c:\internship\Prodify-V2.0\src\run_ensemble.py", line 6, in run_pipeline
[2025-09-24 11:22:49] - logger:write - ERROR - pipe.run_pipeline()  File "c:\internship\Prodify-V2.0\src\pipelines\ensemble_pipeline.py", line 228, in run_pipeline
[2025-09-24 11:22:49] - logger:write - ERROR - train_tfidf_model(self.tfidf_classifier, self.df_train)  File "c:\internship\Prodify-V2.0\src\model_utils.py", line 21, in train_tfidf_model
[2025-09-24 11:22:49] - logger:write - ERROR - tfidf_model.fit(X_train, y_train)  File "c:\internship\Prodify-V2.0\src\models\tfidf_classifier.py", line 41, in fit
[2025-09-24 11:22:49] - logger:write - ERROR - self.clf.fit(X_train, y_train)  File "C:\Users\os255022\AppData\Local\anaconda3\envs\iteration8\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
[2025-09-24 11:22:49] - logger:write - ERROR - return fit_method(estimator, *args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\os255022\AppData\Local\anaconda3\envs\iteration8\Lib\site-packages\sklearn\pipeline.py", line 663, in fit
[2025-09-24 11:22:49] - logger:write - ERROR - self._final_estimator.fit(Xt, y, **last_step_params["fit"])  File "C:\Users\os255022\AppData\Local\anaconda3\envs\iteration8\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
[2025-09-24 11:22:49] - logger:write - ERROR - return fit_method(estimator, *args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\os255022\AppData\Local\anaconda3\envs\iteration8\Lib\site-packages\sklearn\svm\_classes.py", line 321, in fit
[2025-09-24 11:22:49] - logger:write - ERROR - self.coef_, self.intercept_, n_iter_ = _fit_liblinear(^^^^^^^^^^^^^^^  File "C:\Users\os255022\AppData\Local\anaconda3\envs\iteration8\Lib\site-packages\sklearn\svm\_base.py", line 1230, in _fit_liblinear
[2025-09-24 11:22:49] - logger:flush - ERROR - raw_coef_, n_iter_ = liblinear.train_wrap(^^^^^^^^^^^^^^^^^^^^^KeyboardInterrupt
[2025-09-24 11:22:49] - logger:_log - INFO - Operation 'Database disconnection' started
[2025-09-24 11:22:50] - logger:_log - INFO - Operation 'Database disconection' completed
