[2025-09-16 17:42:38] - logger:_log - INFO - Logger initialized. Logs will be saved to C:\internship\Prodify-V2.0\logs\log.txt
[2025-09-16 17:42:44] - warnings:_showwarnmsg - WARNING - c:\internship\Prodify-V2.0\src\utils.py:255: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x_train = torch.tensor(x_train, dtype=model.dtype, device=device)

[2025-09-16 17:42:44] - warnings:_showwarnmsg - WARNING - c:\internship\Prodify-V2.0\src\utils.py:257: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x_test = torch.tensor(x_test, dtype=model.dtype, device=device)

[2025-09-16 17:42:44] - logger:flush - ERROR -   0%|          | 0/500 [00:00<?, ?it/s]
[2025-09-16 17:42:44] - logger:flush - ERROR -   0%|          | 0/500 [00:00<?, ?it/s]
[2025-09-16 17:42:44] - logger:write - ERROR - Traceback (most recent call last):
[2025-09-16 17:42:44] - logger:write - ERROR -   File "c:\internship\Prodify-V2.0\src\main.py", line 199, in <module>
[2025-09-16 17:42:44] - logger:write - ERROR - main()  File "c:\internship\Prodify-V2.0\src\main.py", line 170, in main
[2025-09-16 17:42:44] - logger:write - ERROR - test_gpc_model()  File "c:\internship\Prodify-V2.0\src\main.py", line 67, in test_gpc_model
[2025-09-16 17:42:44] - logger:write - ERROR - model, best_state = gpc_hierarchical_classifier_train(^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "c:\internship\Prodify-V2.0\src\utils.py", line 267, in gpc_hierarchical_classifier_train
[2025-09-16 17:42:44] - logger:write - ERROR - output = model(x_train)^^^^^^^^^^^^^^  File "C:\Users\os255022\AppData\Local\anaconda3\envs\prodify-v2\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
[2025-09-16 17:42:44] - logger:write - ERROR - return self._call_impl(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\os255022\AppData\Local\anaconda3\envs\prodify-v2\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
[2025-09-16 17:42:44] - logger:write - ERROR - return forward_call(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "c:\internship\Prodify-V2.0\src\modules\models.py", line 88, in forward
[2025-09-16 17:42:44] - logger:write - ERROR - family_out = self._mask_logits(^^^^^^^^^^^^^^^^^^  File "c:\internship\Prodify-V2.0\src\modules\models.py", line 76, in _mask_logits
[2025-09-16 17:42:44] - logger:write - ERROR - mask[i, indices] = logits[i, indices]~~~~^^^^^^^^^^^^RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
